### PR TITLE
update to minecraft 1.18

### PR DESCRIPTION
**Pull request by KeyboardKobold**
Updated to work with Minecraft 1.18

- bumped version to 2.2.4
- adapted dependencies to target new spigot release
- replaced reflective field setter with setter provided by class (otherwise exception occurs due to attempt to rewrite final field)

### CODE REVIEW

**Comment by cross** [comment]
Thank you!  Looking forward to getting this on my 1.18 server, please merge when possible.

**Comment by andrew121410** [comment]
While running this on Paper 1.18 build 25 I get this error
```java
[12:35:23 ERROR]: Could not load 'plugins/Images.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: vl$c
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:421) ~[paper-1.18.jar:git-Paper-25]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.jar:git-Paper-25]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-25]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-25]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: vl$c
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.andavin.reflect.Reflection.findClass(Reflection.java:793) ~[Images.jar:?]
        at com.andavin.images.Versioned.getInstance(Versioned.java:58) ~[Images.jar:?]
        at com.andavin.images.Images.<clinit>(Images.java:97) ~[Images.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: vl$c
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at com.andavin.reflect.Reflection.findClass(Reflection.java:793) ~[Images.jar:?]
        at com.andavin.images.Versioned.getInstance(Versioned.java:58) ~[Images.jar:?]
        at com.andavin.images.Images.<clinit>(Images.java:97) ~[Images.jar:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        ... 7 more
```

**Comment by KeyboardKobold** [comment]
> While running this on Paper 1.18 build 25 I get this error

Was Paper supported in the previous version? I can't really comment on your issue, there was only really one line of real java code that was changed by me, not sure where your class loading error is coming from.

On our Spigot 1.18 Server it's running fine, our players are using it without hiccups.

**Comment by andrew121410** [comment]
It's not working on Spigot 1.18 either. Really weird not sure what's causing this issue.

**Comment by cross** [comment]
I tried to build from your fork, @KeyboardKobold , but maven is having none of it. Only 1.8 builds, rest fail.  I'm not sure what the "Ensure that you have the project setup properly with Maven" means.  Let me know if you have a discussion somewhere, I didn't see that I could open a discussion or issue on your fork.....

**Comment by PabloGirol** [comment]
Same issue, it cant resolve dependencies due to every jar except 1.8 from spigot was deleted
now only spigot-api exists. even trying with another repo fails

**Comment by cross** [comment]
@PabloGirol I got it working, I used `<url>http://maven.elmakers.com/repository/</url>
` for the `spigotmc-repo`, and had to only comment out `Images-v1_16_R3` from two places since that repo had all _but_ 1.16.5.  That got me built.  FYI

**Comment by PabloGirol** [comment]
> @PabloGirol I got it working, I used `<url>http://maven.elmakers.com/repository/</url>
> ` for the `spigotmc-repo`, and had to only comment out `Images-v1_16_R3` from two places since that repo had all _but_ 1.16.5.  That got me built.  FYI

Well I didn't even had to comment that, I got s successful build

**Comment by StrixTyphoon** [comment]
I'm having some problems compiling this code I'm kinda new to all this and just shoved all the things I learned from beginners guides to maven and I keep getting the same error spat out at me even after doing the same thing that @cross did to get their build to work (being new I ultimately could've just made a mistake in my code)

I have no idea what it means so I'm hoping someone can help me out

Log file; https://pastebin.com/pDzL8mMR

**Comment by Andavin** [comment]
Hey there! I appreciate the pull request this is quite helpful. It looks pretty good and there's only a couple of things missed (e.g. the cause of the above error). I'm going to merge it in and fix those up; thank you for the help.
