### ISSUE TITLE
Does not work on 1.19

### ISSUE THREAD

**Issue by Gamer101233** [Andavin/Images#74]
When i go to create a image on my server i get this error in console

[15:20:01 WARN]: [Images] Plugin Images v2.3.0 generated an exception while executing task 3098
java.lang.NoSuchMethodError: 'net.minecraft.core.EnumDirection net.minecraft.world.entity.decoration.EntityItemFrame.cv()'
        at com.andavin.images.v1_19_R1.MapHelper.createMap(MapHelper.java:104) ~[images-2.3.0.jar:?]
        at com.andavin.images.MapHelper.createMap(MapHelper.java:79) ~[images-2.3.0.jar:?]
        at com.andavin.images.image.CustomImageSection.show(CustomImageSection.java:141) ~[images-2.3.0.jar:?]
        at com.andavin.images.image.CustomImage.refresh(CustomImage.java:175) ~[images-2.3.0.jar:?]
        at com.andavin.images.command.CreateCommand.lambda$onInteract$5(CreateCommand.java:204) ~[images-2.3.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-81]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-81]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by CloudeLecaw** [comment]
is this paper 1.19.0?

**Comment by Andavin** [comment]
What @CloudeLecaw said is exactly correct. The builds are only guaranteed to work with the most updated minor version of each major version (e.g. 1.19.2 not 1.19.1 etc.)
