### ISSUE TITLE
Logfile spam NoSuchMethodError 1.17.1

### ISSUE THREAD

**Issue by 23Luzi23** [Andavin/Images#24]
Images 2.2.1 spam my log on 1.17.1 server

https://pastebin.com/yBgF1iws

**Comment by CloudeLecaw** [comment]
i agree

happens on /spawn and worldchange to us.
New pictures are not shown to the player until they relog
```
[21:59:48] [Craft Scheduler Thread - 81/WARN]: [Images] Plugin Images v2.2.1 generated an exception while executing task 184542
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
	at com.andavin.images.v1_17_R1.MapHelper.destroyMap(MapHelper.java:114) ~[?:?]
	at com.andavin.images.MapHelper.destroyMaps(MapHelper.java:88) ~[?:?]
	at com.andavin.images.image.CustomImageSection.hide(CustomImageSection.java:153) ~[?:?]
	at com.andavin.images.image.CustomImage.refresh(CustomImage.java:180) ~[?:?]
	at com.andavin.images.Images.refreshImages(Images.java:437) ~[?:?]
	at com.andavin.images.Images.lambda$onMove$9(Images.java:256) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-88]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-88]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by LucidAPs** [comment]
Same here
https://nekobin.com/qowoqokusa

**Comment by CloudeLecaw** [comment]
We hope an Update will come this week. So wait a bit :-)

**Comment by CloudeLecaw** [comment]
Are there any needs or informations about a upcomming 1.17.1 fix? :3

**Comment by Camillo82** [comment]
Can confirm.

After updating to 1.17.1 with the latest plugin version everything seems to work fine, images are being displayed correctly but I'm getting this console spam:

[Images] Plugin Images v2.2.1 generated an exception while executing task 217
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.PacketPlayOutEntityDestroy.<init>(int)'
at com.andavin.images.v1_17_R1.MapHelper.destroyMap(MapHelper.java:114) ~[?:?]
at com.andavin.images.MapHelper.destroyMaps(MapHelper.java:88) ~[?:?]
at com.andavin.images.image.CustomImageSection.hide(CustomImageSection.java:153) ~[?:?]
at com.andavin.images.image.CustomImage.refresh(CustomImage.java:180) ~[?:?]
at com.andavin.images.Images.refreshImages(Images.java:437) ~[?:?]
at com.andavin.images.Images.lambda$onEnable$2(Images.java:172) ~[?:?]
at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
at com.andavin.images.Images.lambda$onEnable$3(Images.java:166) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-100]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-100]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-100]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]

It is happening when I'm going through nether portal weirdly ???

Any fix most appreciated :)

**Comment by DrakMC** [comment]
I have the same problem.

**Comment by Andavin** [comment]
Should be good with the [newest update](https://www.spigotmc.org/resources/custom-images.53036/update?update=412991)
